# Set the I/O standard for SRAM signals
set_property IOSTANDARD LVCMOS33 [get_ports {led_status_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports sram_ce0_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports sram_ce1_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports sram_we_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports sram_oe_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {err_inj_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports err_a_0]
set_property IOSTANDARD LVCMOS33 [get_ports err_sys_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_0]

set_property IOSTANDARD LVCMOS33 [get_ports sram_ce0_n_1]
set_property IOSTANDARD LVCMOS33 [get_ports sram_ce1_n_1]
set_property IOSTANDARD LVCMOS33 [get_ports sram_we_n_1]
set_property IOSTANDARD LVCMOS33 [get_ports sram_oe_n_1]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr_1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data_1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {err_inj_1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports err_a_1]
set_property IOSTANDARD LVCMOS33 [get_ports err_sys_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_1]

# Assign the package pins for SRAM signals
set_property PACKAGE_PIN AA9 [get_ports {led_status_0[0]}]
set_property PACKAGE_PIN AA8 [get_ports {led_status_0[1]}]
set_property PACKAGE_PIN Y10 [get_ports uart_rst_0]
set_property PACKAGE_PIN Y20 [get_ports {sram_data_0[0]}]
set_property PACKAGE_PIN K18 [get_ports {sram_data_0[1]}]
set_property PACKAGE_PIN Y21 [get_ports {sram_data_0[2]}]
set_property PACKAGE_PIN N19 [get_ports {sram_data_0[3]}]
set_property PACKAGE_PIN J18 [get_ports {sram_data_0[4]}]
set_property PACKAGE_PIN N17 [get_ports {sram_data_0[5]}]
set_property PACKAGE_PIN K20 [get_ports {sram_data_0[6]}]
set_property PACKAGE_PIN J17 [get_ports {sram_data_0[7]}]
set_property PACKAGE_PIN N18 [get_ports {sram_data_0[8]}]
set_property PACKAGE_PIN N20 [get_ports {sram_data_0[9]}]
set_property PACKAGE_PIN K19 [get_ports {sram_data_0[10]}]
set_property PACKAGE_PIN L18 [get_ports {sram_data_0[11]}]
set_property PACKAGE_PIN R21 [get_ports {sram_data_0[12]}]
set_property PACKAGE_PIN R20 [get_ports {sram_data_0[13]}]
set_property PACKAGE_PIN P17 [get_ports {sram_data_0[14]}]
set_property PACKAGE_PIN L21 [get_ports {sram_data_0[15]}]
set_property PACKAGE_PIN L16 [get_ports {sram_data_0[16]}]
set_property PACKAGE_PIN L22 [get_ports {sram_data_0[17]}]
set_property PACKAGE_PIN M19 [get_ports {sram_data_0[18]}]
set_property PACKAGE_PIN M20 [get_ports {sram_data_0[19]}]
set_property PACKAGE_PIN K16 [get_ports {sram_data_0[20]}]
set_property PACKAGE_PIN T16 [get_ports {sram_data_0[21]}]
set_property PACKAGE_PIN T17 [get_ports {sram_data_0[22]}]
set_property PACKAGE_PIN G21 [get_ports {sram_data_0[23]}]
set_property PACKAGE_PIN F22 [get_ports {sram_data_0[24]}]
set_property PACKAGE_PIN G20 [get_ports {sram_data_0[25]}]
set_property PACKAGE_PIN F21 [get_ports {sram_data_0[26]}]
set_property PACKAGE_PIN H18 [get_ports {sram_data_0[27]}]
set_property PACKAGE_PIN J22 [get_ports {sram_data_0[28]}]
set_property PACKAGE_PIN J21 [get_ports {sram_data_0[29]}]
set_property PACKAGE_PIN L17 [get_ports {sram_data_0[30]}]
set_property PACKAGE_PIN H17 [get_ports {sram_data_0[31]}]
set_property PACKAGE_PIN F19 [get_ports {sram_data_0[32]}]
set_property PACKAGE_PIN P21 [get_ports {sram_data_0[33]}]
set_property PACKAGE_PIN M17 [get_ports {sram_data_0[34]}]
set_property PACKAGE_PIN G19 [get_ports {sram_data_0[35]}]
set_property PACKAGE_PIN P20 [get_ports {sram_data_0[36]}]
set_property PACKAGE_PIN R19 [get_ports {sram_data_0[37]}]
set_property PACKAGE_PIN H20 [get_ports {sram_data_0[38]}]
set_property PACKAGE_PIN T19 [get_ports {sram_data_0[39]}]

set_property PACKAGE_PIN P16 [get_ports {sram_addr_0[0]}]
set_property PACKAGE_PIN D17 [get_ports {sram_addr_0[1]}]
set_property PACKAGE_PIN E16 [get_ports {sram_addr_0[2]}]
set_property PACKAGE_PIN T18 [get_ports {sram_addr_0[3]}]
set_property PACKAGE_PIN D16 [get_ports {sram_addr_0[4]}]
set_property PACKAGE_PIN R18 [get_ports {sram_addr_0[5]}]
set_property PACKAGE_PIN F18 [get_ports {sram_addr_0[6]}]
set_property PACKAGE_PIN F16 [get_ports {sram_addr_0[7]}]
set_property PACKAGE_PIN N15 [get_ports {sram_addr_0[8]}]
set_property PACKAGE_PIN E19 [get_ports {sram_addr_0[9]}]
set_property PACKAGE_PIN G22 [get_ports {sram_addr_0[10]}]
set_property PACKAGE_PIN E18 [get_ports {sram_addr_0[11]}]
set_property PACKAGE_PIN G15 [get_ports {sram_addr_0[12]}]
set_property PACKAGE_PIN G16 [get_ports {sram_addr_0[13]}]
set_property PACKAGE_PIN E20 [get_ports {sram_addr_0[14]}]
set_property PACKAGE_PIN K21 [get_ports {sram_addr_0[15]}]
set_property PACKAGE_PIN G17 [get_ports {sram_addr_0[16]}]
set_property PACKAGE_PIN P15 [get_ports {sram_addr_0[17]}]
set_property PACKAGE_PIN H19 [get_ports {sram_addr_0[18]}]

set_property PACKAGE_PIN R16 [get_ports sram_ce0_n_0]
set_property PACKAGE_PIN J15 [get_ports sram_ce1_n_0]
set_property PACKAGE_PIN D15 [get_ports sram_we_n_0]
set_property PACKAGE_PIN E15 [get_ports sram_oe_n_0]

set_property PACKAGE_PIN H22 [get_ports {err_inj_0[0]}]
set_property PACKAGE_PIN J20 [get_ports {err_inj_0[1]}]
set_property PACKAGE_PIN K15 [get_ports err_a_0]
set_property PACKAGE_PIN F17 [get_ports err_sys_0]
set_property PACKAGE_PIN E21 [get_ports led_0]

set_property PACKAGE_PIN Y6 [get_ports {sram_data_1[0]}]
set_property PACKAGE_PIN W21 [get_ports {sram_data_1[1]}]
set_property PACKAGE_PIN W5 [get_ports {sram_data_1[2]}]
set_property PACKAGE_PIN U9 [get_ports {sram_data_1[3]}]
set_property PACKAGE_PIN W20 [get_ports {sram_data_1[4]}]
set_property PACKAGE_PIN Y5 [get_ports {sram_data_1[5]}]
set_property PACKAGE_PIN W22 [get_ports {sram_data_1[6]}]
set_property PACKAGE_PIN V22 [get_ports {sram_data_1[7]}]
set_property PACKAGE_PIN V7 [get_ports {sram_data_1[8]}]
set_property PACKAGE_PIN R6 [get_ports {sram_data_1[9]}]
set_property PACKAGE_PIN U22 [get_ports {sram_data_1[10]}]
set_property PACKAGE_PIN T22 [get_ports {sram_data_1[11]}]
set_property PACKAGE_PIN T6 [get_ports {sram_data_1[12]}]
set_property PACKAGE_PIN U6 [get_ports {sram_data_1[13]}]
set_property PACKAGE_PIN U5 [get_ports {sram_data_1[14]}]
set_property PACKAGE_PIN U12 [get_ports {sram_data_1[15]}]
set_property PACKAGE_PIN U14 [get_ports {sram_data_1[16]}]
set_property PACKAGE_PIN U11 [get_ports {sram_data_1[17]}]
set_property PACKAGE_PIN T4 [get_ports {sram_data_1[18]}]
set_property PACKAGE_PIN U4 [get_ports {sram_data_1[19]}]
set_property PACKAGE_PIN R15 [get_ports {sram_data_1[20]}]
set_property PACKAGE_PIN W10 [get_ports {sram_data_1[21]}]
set_property PACKAGE_PIN W11 [get_ports {sram_data_1[22]}]
set_property PACKAGE_PIN U17 [get_ports {sram_data_1[23]}]
set_property PACKAGE_PIN V19 [get_ports {sram_data_1[24]}]
set_property PACKAGE_PIN V17 [get_ports {sram_data_1[25]}]
set_property PACKAGE_PIN V18 [get_ports {sram_data_1[26]}]
set_property PACKAGE_PIN U16 [get_ports {sram_data_1[27]}]
set_property PACKAGE_PIN AB17 [get_ports {sram_data_1[28]}]
set_property PACKAGE_PIN AA17 [get_ports {sram_data_1[29]}]
set_property PACKAGE_PIN AA14 [get_ports {sram_data_1[30]}]
set_property PACKAGE_PIN Y16 [get_ports {sram_data_1[31]}]
set_property PACKAGE_PIN AA16 [get_ports {sram_data_1[32]}]
set_property PACKAGE_PIN W16 [get_ports {sram_data_1[33]}]
set_property PACKAGE_PIN Y14 [get_ports {sram_data_1[34]}]
set_property PACKAGE_PIN AB16 [get_ports {sram_data_1[35]}]
set_property PACKAGE_PIN U15 [get_ports {sram_data_1[36]}]
set_property PACKAGE_PIN W13 [get_ports {sram_data_1[37]}]
set_property PACKAGE_PIN W18 [get_ports {sram_data_1[38]}]
set_property PACKAGE_PIN V13 [get_ports {sram_data_1[39]}]

set_property PACKAGE_PIN AB20 [get_ports {sram_addr_1[0]}]
set_property PACKAGE_PIN W6 [get_ports {sram_addr_1[1]}]
set_property PACKAGE_PIN AA19 [get_ports {sram_addr_1[2]}]
set_property PACKAGE_PIN V12 [get_ports {sram_addr_1[3]}]
set_property PACKAGE_PIN Y19 [get_ports {sram_addr_1[4]}]
set_property PACKAGE_PIN W12 [get_ports {sram_addr_1[5]}]
set_property PACKAGE_PIN M16 [get_ports {sram_addr_1[6]}]
set_property PACKAGE_PIN U20 [get_ports {sram_addr_1[7]}]
set_property PACKAGE_PIN M15 [get_ports {sram_addr_1[8]}]
set_property PACKAGE_PIN V20 [get_ports {sram_addr_1[9]}]
set_property PACKAGE_PIN AB21 [get_ports {sram_addr_1[10]}]
set_property PACKAGE_PIN Y8 [get_ports {sram_addr_1[11]}]
set_property PACKAGE_PIN AB14 [get_ports {sram_addr_1[12]}]
set_property PACKAGE_PIN W15 [get_ports {sram_addr_1[13]}]
set_property PACKAGE_PIN T21 [get_ports {sram_addr_1[14]}]
set_property PACKAGE_PIN AA13 [get_ports {sram_addr_1[15]}]
set_property PACKAGE_PIN AA18 [get_ports {sram_addr_1[16]}]
set_property PACKAGE_PIN Y13 [get_ports {sram_addr_1[17]}]
set_property PACKAGE_PIN W17 [get_ports {sram_addr_1[18]}]

set_property PACKAGE_PIN AB19 [get_ports sram_ce0_n_1]
set_property PACKAGE_PIN W7 [get_ports sram_ce1_n_1]
set_property PACKAGE_PIN V10 [get_ports sram_we_n_1]
set_property PACKAGE_PIN V9 [get_ports sram_oe_n_1]

set_property PACKAGE_PIN AA21 [get_ports {err_inj_1[0]}]
set_property PACKAGE_PIN AB15 [get_ports {err_inj_1[1]}]
set_property PACKAGE_PIN U7 [get_ports err_a_1]
set_property PACKAGE_PIN Y18 [get_ports err_sys_1]
set_property PACKAGE_PIN Y11 [get_ports led_1]

#set_output_delay -clock ext_clk_200M -max 3.0 [get_ports {sram_we_n_0}]
#set_output_delay -clock ext_clk_200M -min 1.0 [get_ports {sram_oe_n_0}]
#set_output_delay -clock ext_clk_200M -max 3.0 [get_ports {sram_oe_n_0}]

#set_output_delay -clock ext_clk_200M -min 1.0 [get_ports {sram_we_n_1}]
#set_output_delay -clock ext_clk_200M -max 3.0 [get_ports {sram_we_n_1}]
#set_output_delay -clock ext_clk_200M -min 1.0 [get_ports {sram_oe_n_1}]
#set_output_delay -clock ext_clk_200M -max 3.0 [get_ports {sram_oe_n_1}]


#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]


