# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.srcs/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0.xci
# IP: The module: 'sram_test_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_test_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_test_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_test_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.srcs/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0.xci
# IP: The module: 'sram_test_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_test_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_test_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_test_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
