#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define USE_SOFTETH_ON_ZYNQ_0
#define PLATFORM_EMAC_BASEADDR XPAR_XEMACPS_0_BASEADDR
#define STDOUT_IS_PS7_UART
#define PLATFORM_ZYNQ 


#endif
