# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/HuaweiMoveData/Users/chx/Desktop/Sram_test/constrain.xdc

# Block Designs: bd/sram_test/sram_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test || ORIG_REF_NAME==sram_test} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_processing_system7_0_0/sram_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_processing_system7_0_0 || ORIG_REF_NAME==sram_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_xbar_0/sram_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_xbar_0 || ORIG_REF_NAME==sram_test_xbar_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_auto_pc_0/sram_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_auto_pc_0 || ORIG_REF_NAME==sram_test_auto_pc_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_axi_interconnect_0_0/sram_test_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_axi_interconnect_0_0 || ORIG_REF_NAME==sram_test_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_proc_sys_reset_0_0/sram_test_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_proc_sys_reset_0_0 || ORIG_REF_NAME==sram_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_axi_apb_bridge_0_0/sram_test_axi_apb_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_axi_apb_bridge_0_0 || ORIG_REF_NAME==sram_test_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_axi_apb_bridge_1_0/sram_test_axi_apb_bridge_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_axi_apb_bridge_1_0 || ORIG_REF_NAME==sram_test_axi_apb_bridge_1_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_apb_slave_0_0/sram_test_apb_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_apb_slave_0_0 || ORIG_REF_NAME==sram_test_apb_slave_0_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_top_0_0/sram_test_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_top_0_0 || ORIG_REF_NAME==sram_test_top_0_0} -quiet] -quiet

# IP: bd/sram_test/ip/sram_test_top_1_0/sram_test_top_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sram_test_top_1_0 || ORIG_REF_NAME==sram_test_top_1_0} -quiet] -quiet

# XDC: d:/HuaweiMoveData/Users/chx/Desktop/Sram_test/sram_test/sram_test.gen/sources_1/bd/sram_test/sram_test_ooc.xdc
